// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATURnh1109Lm2Vu0Y362GHwvK2s7NyOcE',
    appId: '1:99899272148:web:089d01cdce14a87c1a8441',
    messagingSenderId: '99899272148',
    projectId: 'foodapp-e2110',
    authDomain: 'foodapp-e2110.firebaseapp.com',
    storageBucket: 'foodapp-e2110.appspot.com',
    measurementId: 'G-56HTWJXS18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMu4BZRBS5l7QmnTEPr5sNrimwI0Ogn0g',
    appId: '1:99899272148:android:65245f42cc064a401a8441',
    messagingSenderId: '99899272148',
    projectId: 'foodapp-e2110',
    storageBucket: 'foodapp-e2110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKAT6CWm2tp0DZQD4MVXTZo2lrQDam0Y',
    appId: '1:99899272148:ios:ad0e18ba1efc57181a8441',
    messagingSenderId: '99899272148',
    projectId: 'foodapp-e2110',
    storageBucket: 'foodapp-e2110.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIKAT6CWm2tp0DZQD4MVXTZo2lrQDam0Y',
    appId: '1:99899272148:ios:a102dc5cb5d851921a8441',
    messagingSenderId: '99899272148',
    projectId: 'foodapp-e2110',
    storageBucket: 'foodapp-e2110.appspot.com',
    iosBundleId: 'com.example.foodapp.RunnerTests',
  );
}
